version=1.1.0
message=New version available. Click Update to download it.
downloadUrl.windows=https://github.com/beatzgaming12-glitch/projectlmao/releases/download/v1.1.0/ProjectLMAO-v1.0.0-current.zip
